# Generated by ChatGPT for adding upload_session field to Attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_alter_attachment_entry_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='upload_session',
            field=models.CharField(max_length=64, null=True, blank=True, db_index=True),
        ),
    ]
