"""
Django settings for ll_project project.

Generated by 'django-admin startproject' using Django 4.1b1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from pathlib import Path
import mimetypes
import os
from urllib.parse import urlparse

# 加载 .env（若存在），便于在服务器通过 .env 管理配置而不必 export 环境变量
try:
    from dotenv import load_dotenv  # type: ignore
    # 使用 override=True 让 .env 中的变量覆盖已存在的同名环境变量（例如之前 export 过 DEBUG=False 的残留），
    # 避免出现“修改 .env 后仍旧读取旧值”的困惑。
    _env_loaded = load_dotenv(
        dotenv_path=Path(__file__).resolve().parent.parent / '.env',
        override=True,
    )
except Exception:
    _env_loaded = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'dev-insecure-key-change-me')
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# 动态允许主机：Render 使用 RENDER_EXTERNAL_HOSTNAME；阿里云 ECS/容器需通过环境变量 ALLOWED_HOSTS_EXTRA 指定公网域名/IP
_render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
ALLOWED_HOSTS = ['localhost', '127.0.0.1'] + ([_render_host] if _render_host else [])
# 额外主机（逗号分隔），例如你的阿里云公网 IP 或绑定的域名 diary.example.com
_extra_hosts = os.getenv('ALLOWED_HOSTS_EXTRA', '')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]

# CSRF 可信任域名：生产时根据外部主机/自定义域名填充（HTTPS 域名）
CSRF_TRUSTED_ORIGINS = []
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_render_host}')
_extra_csrf = os.getenv('CSRF_TRUSTED_ORIGINS_EXTRA', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf.split(',') if o.strip()]

# Application definition

INSTALLED_APPS = [
    # My apps.
    'learning_logs',
    'accounts',

    # Third party apps.
    'django_bootstrap5',
    # Cloudinary（有 CLOUDINARY_URL 时生效，见下方条件配置）

    # Default django apps.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise 静态文件服务（放在 SecurityMiddleware 之后）
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'll_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'learning_logs.context_processors.background_image',
                'learning_logs.context_processors.background_video',
            ],
        },
    },
]

WSGI_APPLICATION = 'll_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Render Postgres: 若存在 DATABASE_URL 则解析使用
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # 兼容 postgres:// 前缀
    if DATABASE_URL.startswith('postgres://'):
        DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
    url = urlparse(DATABASE_URL)
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': url.path.lstrip('/'),
        'USER': url.username,
        'PASSWORD': url.password,
        'HOST': url.hostname,
        'PORT': url.port or 5432,
        'CONN_MAX_AGE': 300,
    }


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# My settings.
LOGIN_REDIRECT_URL = 'learning_logs:index'
LOGOUT_REDIRECT_URL = 'learning_logs:index'
LOGIN_URL = 'accounts:login'

# Ensure uncommon extensions are served with correct MIME types (e.g., custom H.264 files)
# Some users may place files with non-standard extensions like .m246; map them to video/mp4
mimetypes.add_type('video/mp4', '.m246', strict=False)
mimetypes.add_type('video/mp4', '.mp4', strict=False)

# Background video file or absolute URL. Leave blank to disable local static video preload.
# Example for Cloudinary hosted video:
# BACKGROUND_VIDEO = 'https://res.cloudinary.com/<cloud_name>/video/upload/v1234567890/your_clip.mp4'
BACKGROUND_VIDEO = os.getenv('BACKGROUND_VIDEO', '')
# 控制 <video preload> 策略：auto/metadata/none（默认 metadata，避免与首屏资源争带宽导致卡顿）
BACKGROUND_VIDEO_PRELOAD = os.getenv('BACKGROUND_VIDEO_PRELOAD', 'metadata').lower()

# 显式控制 Cookie 的 Secure 标志（默认在开发环境关闭，生产 DEBUG=False 时会在下方强制开启）。
# 如需在开发/HTTP 环境中确保不携带 Secure，可在 .env 中设置：
#   CSRF_COOKIE_SECURE=false
#   SESSION_COOKIE_SECURE=false
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'false').lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'false').lower() in ('1', 'true', 'yes')

#################################################################
# 生产安全附加设置（当 DEBUG=False 时启用更加安全的选项）
#################################################################
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))  # 可在环境变量中设置，如 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # 日志基本配置：Render 的 stdout/stderr 会被收集
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'default': {
                'format': '[{asctime}] {levelname} {name}: {message}',
                'style': '{'
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'default'
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }

# -----------------------------
# Cloudinary 媒体存储（可选）
# -----------------------------
# 若设置了 CLOUDINARY_URL（形如 cloudinary://api_key:api_secret@cloud_name），
# 则自动启用 Cloudinary 作为默认文件存储，以持久保存用户上传的附件。
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL')
if CLOUDINARY_URL:
    # 仅在存在配置时才注册依赖 app，避免本地未安装时报错
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # 可选：自定义媒体 URL 前缀（一般由 Cloudinary 返回的 URL 决定，这里保持默认即可）